"""cascade change 3

Revision ID: bf14ce8c5c9c
Revises: f4a00a4e4fd0
Create Date: 2023-09-20 16:37:13.395387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf14ce8c5c9c"
down_revision: Union[str, None] = "f4a00a4e4fd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
