FROM python:3.11

WORKDIR /app


COPY ./test_requirements.txt ./

RUN apt-get update && apt-get install -y python3-dev
RUN pip install --upgrade pip
RUN pip install -r test_requirements.txt
RUN pip install --no-cache-dir -r test_requirements.txt

COPY /auth ./auth
COPY /aws ./aws
COPY /database ./database
COPY /exceptions ./exceptions
COPY /images ./images
COPY /logs ./logs
COPY /models ./models
COPY /routes ./routes
COPY /schema ./schema
COPY /tests ./tests
COPY ./test.env ./.env
COPY ./celery_app.py ./
COPY ./logging_conf.py ./
COPY ./main.py ./
COPY ./settings.py ./
COPY ./pyproject.toml ./
COPY ./tox.ini ./